### ISSUE TITLE
user/role for commercial and govcloud S3 bucket selector reversed

### ISSUE THREAD

**Issue by carter3d** [awslabs/aws-gov-cloud-import#1]
The commercial region role is referred to as a user and the GovCloud user is referred to as a role on the S3 import page.

![screen shot 2018-06-26 at 9 15 31 am](https://user-images.githubusercontent.com/12088157/41922560-a2025292-7922-11e8-823f-4132ee1377c6.png)

**Comment by awsjason** [comment]
All swapped back into place.  Thank you.
