### ISSUE TITLE
Can't run gov-cloud-import-install.sh more than once

### ISSUE THREAD

**Issue by todds02** [awslabs/aws-gov-cloud-import#12]
It looks like when gov-cloud-import-install.sh is executed, the cloudformation/gov-cloud-import-commercial.json file is modified, replacing the BUCKET_BASE template anchor with the random S3 bucket used for the run.  Subsequent runs will all have their CloudFormation runs fail with "NoSuchBucket" errors when attemping to copy the lambda functions.

It looks like this affects the most recent commit, as well - the template anchor appears to have been removed: https://github.com/awslabs/aws-gov-cloud-import/commit/792534c7bdd51953354c0162fd4ded5102c76339

**Comment by awsjason** [comment]
Sorry for the delay.  This was intended as CF needs the file with the names.  If you want to run installer again, please re-clone the repo and start again.

**Comment by todds02** [comment]
It seems like this is fixable by simply making a copy of the affected file(s), rather than modifying the originals.

Regardless, I believe it's worthy of a note in the documentation (if one is there, I missed it). This behavior results in a non-obvious error message after several minutes of the script running.  If I remember correctly, the script itself appears to hang, you need to navigate to the AWS console to see that the CF stack deployment had failed.
