### ISSUE TITLE
Unable to import server image from AWS Marketplace AMI?

### ISSUE THREAD

**Issue by RandyForte** [awslabs/aws-gov-cloud-import#14]
Is there any specific limitation to this tool or gov cloud that would not allow for an image from a server generated by a AWS Marketplace image to not be imported? I have a server that was made from WordPress Certified by Bitnami and Automattic image and it seems to fail each time. My Amazon Linux seems to import just fine and im not sure if the issue is related to the fact that the server is from an AWS marketplace image.

**Comment by awsjason** [comment]
It could be because it' an Issue with Marketplace images.  They can have software on the image that may prevent it from working properly.
