### ISSUE TITLE
Imported AMI is not does not have enaSupport enabled

### ISSUE THREAD

**Issue by psychosquirrel85** [awslabs/aws-gov-cloud-import#15]
Hello,

I am trying to import an AMI from my commercial account into GovCloud.  

Commercial Account has a t3 instance which I created an AMI from.  This AMI has ENA support enabled though inheritance.  

When I import the AMI into GovCloud us-gov-east-1 the enaSupport is missing and I am unable to launch a t3 instance because it is greyed out. 

How can this issue be resolved.  I notice in the blog post regarding this tool it makes no mention of ENA support. 

Please advise.

**Comment by awsjason** [comment]
Can you try making another image from the Snapshot associated with the AMI?

**Comment by scardetto** [comment]
@awsjason I ran into the same issue.  Your suggestion of creating a new image from the copied snapshot fixed the problem.   Do you know why this is happening?

**Comment by awsjason** [comment]
@scardetto Snapshots don't have all the AMI info contain.  e.g., a network adapter.  They are just a snapshot of the volume itself.

**Comment by pkazi** [comment]
Hi @scardetto , I also faced same issue and suggestion of creating new AMI from copied snapshot worked for me.
Is there any way to fix this problem in this tool itself?

**Comment by scardetto** [comment]
This is not my tool, but my understanding is that creating the snapshot eliminates the hardware information from the image which then allows it to be re-created properly.  I don't know if it's possible for the tool to do this automatically. That would be a question for @awsjason.
