### ISSUE TITLE
CloudFormation Stack Failure

### ISSUE THREAD

**Issue by groovemaps** [awslabs/aws-gov-cloud-import#17]
Trying run the installation script `./gov-cloud-import-install.sh` and it is failing when attempting to create the cloud formation stack in our commercial region. I've been running this with AWS support and it failed twice. There seems to be an invalid status being returned, including the terminal output below:

```
Starting gov-cloud-import deployment to us-gov-east-1 and us-east-2.


Making S3 Bucket in us-east-2

Copying App to S3 Bucket in us-east-2

Compressing Lambda Functions
updating: index.js (deflated 71%)

Synchronizing files to S3 bucket
Deploying CloudFormations
arn:aws:cloudformation:us-east-2:xxxxxxx:stack/gov-cloud-import/xxxxxxx
arn:aws-us-gov:cloudformation:us-gov-east-1:xxxxxxxxx:stack/gov-cloud-import/xxxxxxx
arn:aws-us-gov:cloudformation:us-gov-east-1:xxxxxxxxx:stack/gov-cloud-import-vmimport/xxxxxxxx

Script will check Cloudformation status every 30 seconds until complete.
This will take 5+ mins to complete.

2019-10-30_18:02:51 AWS GovCloud (US) Status: CREATE_IN_PROGRESS
2019-10-30_18:02:51 AWS Status: CREATE_IN_PROGRESS
2019-10-30_18:03:23 AWS GovCloud (US) Status: CREATE_IN_PROGRESS
2019-10-30_18:03:23 AWS Status: user.
```

Status `user` seems to be incorrect. Not sure what else that could imply...

**Comment by awsjason** [comment]
What did the CFN template status show in GovCloud and AWS?  Did they complete?

**Comment by groovemaps** [comment]
@awsjason `ROLLBACK_COMPLETE` 

So nope they did not complete, the status being returned is very suspect.

**Comment by awsjason** [comment]
Soooo... What was the error?  Why didn't it complete?

**Comment by groovemaps** [comment]
No idea... I did not see anything of value in the console ... even AWS Support went ¯\_(ツ)_/¯

**Comment by ghu459** [comment]
I had the same issue, the cloudformation stack failed on snsSubscribe with the following error:
`Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 3b69fdfe-5536-41e4-940a-2e059149da8b)`
I tried running it again and it failed at other steps but with the same error

**Comment by awsjason** [comment]
@ghu459 Match up the s3 Bucket in the template to see if it exists.  I'd suggest deleting your git clone and starting from scratch.

**Comment by aderbique** [comment]
> @ghu459 Match up the s3 Bucket in the template to see if it exists. I'd suggest deleting your git clone and starting from scratch.

Strange. I just incurred this same issue today starting with a fresh git clone. Creates fine in GovCloud, but the stack fails in commercial. Is the commercial stack looking to an external S3 bucket for an object that no longer exists?

**Comment by awsjason** [comment]
You can verify the bucket it attempted to reach in the CFT?  Nothing is external.  Everything is done inside the account you gave creds for deploying.
