### ISSUE TITLE
 aws: command not found , [: ==: unary operator expected

### ISSUE THREAD

**Issue by manojraj185** [awslabs/aws-gov-cloud-import#19]
I was trying to import an AMI from commercial AWS account to aws gov. Both the keys used for the script have admin privileges for the respective account. This is where the script is stuck as of now:
------------
/gov-cloud-import-install.sh: line 202: aws: command not found
./gov-cloud-import-install.sh: line 205: aws: command not found
Copying App to S3 Bucket in us-west-2

./gov-cloud-import-install.sh: line 210: aws: command not found
Compressing Lambda Functions

  adding: index.js (deflated 78%)
  adding: index.js (deflated 74%)
  adding: index.js (deflated 80%)
  adding: index.js (deflated 78%)
  adding: index.js (deflated 79%)
  adding: index.js (deflated 70%)
  adding: index.js (deflated 71%)
  adding: index.js (deflated 68%)
  adding: index.js (deflated 73%)
  adding: index.js (deflated 73%)
  adding: index.js (deflated 68%)
  adding: index.js (deflated 72%)
  adding: index.js (deflated 75%)
  adding: index.js (deflated 73%)
  adding: index.js (deflated 75%)
  adding: index.js (deflated 71%)

Synchronizing files to S3 bucket
./gov-cloud-import-install.sh: line 239: aws: command not found
Deploying CloudFormations
./gov-cloud-import-install.sh: line 243: aws: command not found
./gov-cloud-import-install.sh: line 244: aws: command not found
./gov-cloud-import-install.sh: line 246: aws: command not found

Script will check Cloudformation status every 30 seconds until complete.
This will take 5+ mins to complete.

./gov-cloud-import-install.sh: line 256: aws: command not found
./gov-cloud-import-install.sh: line 257: aws: command not found
./gov-cloud-import-install.sh: line 259: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 259: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 262: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 268: [: ==: unary operator expected
...
./gov-cloud-import-install.sh: line 262: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 268: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 256: aws: command not found
./gov-cloud-import-install.sh: line 257: aws: command not found
/gov-cloud-import-install.sh: line 259: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 259: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 262: [: ==: unary operator expected
./gov-cloud-import-install.sh: line 268: [: ==: unary operator expected
------------ 
I kept script running for long time. I dont see any cloud formation in my aws commercial account. I used the recent script on Jan 28th,2020. Any help with respect to debugging this would be appreciated. - Thanks

**Comment by awsjason** [comment]
Looks like an issue with the creation of the S3 policy:
`aws s3api put-bucket-policy --bucket gov-cloud-import-$RAND --policy file://policy.json --profile com12345`

Did the bucket get made?  Can you put the policy from the script on the bucket?

**Comment by manojraj185** [comment]
This issue got resolved after trying the script from another unix vm. Probably some installation was missing. I got the URL to submit the AMI import. But in the email notification, I received status as ""dest":"failed". How can i track, where exactly it failed?

**Comment by manojraj185** [comment]
Update: I found that we can track the running status from the state machine URL link. I submitted the import image again. Presently its still running phase , been running for past two hours. Fingers crossed.

**Comment by manojraj185** [comment]
Update: The state machine now shows Failed. Digging through the cloudwatch logs of EC2 worker, I see this error: "InvalidArgument: Part number must be an integer between 1 and 10000, inclusive" and "Sent Task Failure to StepFunctions". Any idea, what this error refers to? And how to resolve it?

**Comment by awsjason** [comment]
@manojraj185 I'd look at the cloudwatch logs for the ec2.  Part number is for S3.  What is size your attempting to transfer?

**Comment by manojraj185** [comment]
I saw that error in cloudwatch logs of ec2, "/gov-cloud-import/EC2Worker".  I also see this error message: "{"errno":-5,"code":"EIO","syscall":"read"}"

The size of the AMI is around 150GB, i guess.

**Comment by awsjason** [comment]
@manojraj185 Please review the readme and the apps limits...

**Comment by manojraj185** [comment]
I dont think its because of the app limit , I got stuck in the issue. I tried the same steps on an AMI which is less than 100 GB. But I still see, it got stuck and exited with TimeOut error at this state: ec2s3Copy. "statusCode": 400
