### ISSUE TITLE
Hung at S3 Copy Status

### ISSUE THREAD

**Issue by gumho** [awslabs/aws-gov-cloud-import#2]
When copying from us-west-2 to us-gov-west-1, my image import became stuck at "S3 Copy Status". When I looked at the ActivityStarted for "S3 Copy Status", all I saw was the error message:

`{
  "workerName": null
}`

Given that both sides of the account have Administrator access and I have ownership of the image to be transferred, I'm inclined to believe this is a bug.

**Comment by awsjason** [comment]
Can you paste the cloudwatch logs for the EC2 worker?  May want to obscure the bucket names if they are in there.

**Comment by gumho** [comment]
Turns out the `{ "workerName": null}` was a red herring and not actually an error message. The image ended up getting copied over successfully after waiting a long while.

**Comment by gvr159** [comment]
Having the same issue. The step function has been hanging on "S3 Copy Status" for many hours. I'm inclined to leave it running as no failures have been reported, but would appreciate some more context. @gumho do you recall roughly how long it took to process? Or @awsjason could you shine some light on how long I should expect to wait, or if there actually is a bug? I am trying to transfer a 50 GiB AMI, left it running for 16 hours and still hanging...

**Comment by AmudhaNila** [comment]
I am facing the same issue too. The flow is stuck at "S3 Copy Status" for a day. From EC2Worker logs, I can see the gov-cloud-import.js is trying to start with different node PIDs but never reaches running state.

Wed Mar 20 2019 08:25:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2765
Wed Mar 20 2019 08:30:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2878
Wed Mar 20 2019 08:35:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2995
Wed Mar 20 2019 08:40:03 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2137

**Comment by awsjason** [comment]
@gvr159 Please check the EC2Worker log.  If its like @AmudhaNila issue, you need to terminate the worker and have it spawn a new instance.
