### ISSUE TITLE
Stuck in S3 Copy status and timeout

### ISSUE THREAD

**Issue by manojraj185** [awslabs/aws-gov-cloud-import#20]
Hi,
My state machine was stuck in s3 copy status for 2 hours and then it exited , stating Timeout. The Size of AMI, im trying is 95Gb. 

Task Timed out, Status code 400. 

Do I have to increase the timeout period, for it to continue? If so, how do I do that?

Or , Is something else wrong, which might have led to this? All I see , from EC2 worker logs in cloudwatch, is timeout error and then exited. I couldn't find any other logs.

**Comment by awsjason** [comment]
You have access to everything.  Its open sourced.  Please post the logs and start from where the job was accepted by the EC2.

**Comment by manojraj185** [comment]
-------------
2020-02-07

19:03:32
Fri Feb 07 2020 19:03:28 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 15372

19:04:31
Fri Feb 07 2020 19:04:30 GMT+0000 (UTC) No New Image Import Tasks

19:04:31
Fri Feb 07 2020 19:04:30 GMT+0000 (UTC) No New S3 Sync Tasks

19:04:35
Fri Feb 07 2020 19:04:34 GMT+0000 (UTC) 1581104009747 Time at which to terminate instance.

19:05:02
Fri Feb 07 2020 19:05:01 GMT+0000 (UTC) gov-cloud-import.js is running. Node PID: 15372

19:05:36
Fri Feb 07 2020 19:05:36 GMT+0000 (UTC) No New Image Import Tasks

19:05:36
Fri Feb 07 2020 19:05:36 GMT+0000 (UTC) No New S3 Sync Tasks

19:05:40
Fri Feb 07 2020 19:05:39 GMT+0000 (UTC) 1581104009747 Time at which to terminate instance.

19:06:07
Fri Feb 07 2020 19:06:06 GMT+0000 (UTC) ***New Task***

19:06:07
Fri Feb 07 2020 19:06:06 GMT+0000 (UTC) {"image":"ami-0dfb9f165ad86c353","region":"us-west-2","os":"Linux","waitMove":"60","waitVol":"15","waitEc2":"15","topic":"gov-cloud-import-image","ec2":"pending","imageNew":"ami-0156c51708f9fa910","status":"running","volumeId":"vol-08c2469f4194d039e","volume":{"status":"available"},"cleanUp":"Snapshot removed","taskToken":"AAAAKgAAAAIAAAAAAAAAAX36yHQlU4Rfxqs

19:06:07
Fri Feb 07 2020 19:06:07 GMT+0000 (UTC) {"message":"Cannot attach volume 'vol-08c2469f4194d039e' with Marketplace codes as the instance 'i-0797d6e4e8b430929' is not in the 'stopped' state.","code":"IncorrectInstanceState","time":"2020-02-07T19:06:07.043Z","requestId":"0d14b325-9ee2-4e32-ac19-04ba3e34eec2","statusCode":400,"retryable":false,"retryDelay":52.95197870935095}

19:06:07
Fri Feb 07 2020 19:06:07 GMT+0000 (UTC) IncorrectInstanceState: Cannot attach volume 'vol-08c2469f4194d039e' with Marketplace codes as the instance 'i-0797d6e4e8b430929' is not in the 'stopped' state.
Fri Feb 07 2020 19:06:07 GMT+0000 (UTC) IncorrectInstanceState: Cannot attach volume 'vol-08c2469f4194d039e' with Marketplace codes as the instance 'i-0797d6e4e8b430929' is not in the 'stopped' state.

19:06:41
Fri Feb 07 2020 19:06:40 GMT+0000 (UTC) No New S3 Sync Tasks
-------------

This is the recent error which we are getting. The AMI size is just 8GB. There is no instance running based out of it. Yet I get the error Incorrect Instance State. The instance id mentioned above in the logs, is the gov-cloud-import-ec2 instance. Whaat script/function do I have to correct to make the instance stop and make sure the volume gets attached?

**Comment by awsjason** [comment]
The problem is here:
Fri Feb 07 2020 19:06:07 GMT+0000 (UTC) {"message":"**Cannot attach volume 'vol-08c2469f4194d039e'** with Marketplace codes as the instance 'i-0797d6e4e8b430929' is not in the 'stopped' state.","code":"IncorrectInstanceState","time":"2020-02-07T19:06:07.043Z","requestId":"0d14b325-9ee2-4e32-ac19-04ba3e34eec2","statusCode":400,"retryable":false,"retryDelay":52.95197870935095}

**Comment by manojraj185** [comment]
Yes, I understand the problem is this. But how do I fix this? What code/function handles, shutting down of the import-ec2 instance?

**Comment by awsjason** [comment]
That's beyond the scope of the support for this software.  I'd try to add it manually while the instance is running.  if that wont work, please use AWS Support to troubleshoot the issue.

**Comment by awsjason** [comment]
If you don't want it to shutdown, you can SSH into the EC2 and kill the nodejs script running.  This will keep it running.
