### ISSUE TITLE
Validation error with Lambda function name.

### ISSUE THREAD

**Issue by skhadka-securus** [awslabs/aws-gov-cloud-import#21]
I am seeing this error trying to copy the ami from the gui.

ValidationException: 1 validation error detected: Value 'Not Installed' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?

Also got this error with the install script but it completed sucessfully
zip error: Could not create output file (../makeVolume.zip)
zip I/O error: Permission denied
zip error: Could not create output file (../makeVolumeStatus.zip)
zip I/O error: Permission denied
zip error: Could not create output file (../moveImage.zip)
zip I/O error: Permission denied
zip error: Could not create output file (../moveStatus.zip)
.....

![image](https://user-images.githubusercontent.com/55754315/74458934-0d8e4800-4e50-11ea-95e4-e333e1dcaca2.png)

**Comment by awsjason** [comment]
Look like a permission error on your laptop or EC2 to access the file.  Did the Lambda's get installed?  Can you open up and see code in them?

**Comment by skhadka-securus** [comment]
Yes there is, i see all lambda functions have code. 
I did need to change the us-east-2 to us-east-1 in the install script for my build.

**Comment by skhadka-securus** [comment]
I tried again from scratch this morning. No Lambda errors either. Everything completed successfully until i hit submit and still see the error. 

ValidationException: 1 validation error detected: Value 'Not Installed' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?

![image](https://user-images.githubusercontent.com/55754315/74668845-ab915380-516b-11ea-85f2-850345edddf4.png)

**Comment by skhadka-securus** [comment]
Or the issue may lie in the api keys input. 

It successfully validates the api keys for commercial account but fails for gov  but the input only has AWS govcloud regions. Or is that intended ?
![image](https://user-images.githubusercontent.com/55754315/74671591-1e50fd80-5171-11ea-98d3-2b0e0f301487.png)

**Comment by awsjason** [comment]
This doesn't work in us-east-1.  If you changed the code, you'll need to support as your working in an untested manor.  If you need help with an normal install, please try that.  Thanks.

**Comment by awsjason** [comment]
Will close the case and please reopen if you run into issues.

**Comment by aakifshaikh** [comment]
I am getting this error? Does it work in us-east-1 region or not?
![Screen Shot 2021-08-26 at 7 26 59 PM](https://user-images.githubusercontent.com/27826591/131052733-ac4b1671-3cf6-4379-a15d-0dacaf98a319.png)

CLI version
aws-cli/1.19.5 Python/3.9.1 Darwin/20.6.0 botocore/1.20.96
