### ISSUE TITLE
100GB Limit

### ISSUE THREAD

**Issue by jrvh** [awslabs/aws-gov-cloud-import#23]
We have AMIs that are 110/200/210 GB insize. We would really like to use this tool to move then to govcloud. Asking for a feature improvement to support larger AMI sizes.

Trying to understand where the existing 100GB limit is coming from, and what options there are to go beyond 100GB?

**Comment by awsjason** [comment]
The size is based on a timeout value in step functions for the copy step to work.  There is no hard limit, I've only tested up to 100G.  Please feel free to test further by adjusting the timeout in Step Functions.

**Comment by jrvh** [comment]
So I have been looking into this, and could use come clarification. When you refer to the timeouts in the stepfunctions. You mean :

In AWS Console, going to StepFunctions --> ImageStateMachine-XXXXX

Playing around with : 
"S3 Copy Status" and the TimeoutSeconds?

And/Or : 

in AWS Console --> lambda --> edit gov-cloud-import-initStepFunction-XXXXXXX

and playing around with 'waitMove', 'waitEC2' and 'waitVol'

Spent some time playing with all the above and not had much luck. But wanted to confirm I am in the right spot?

Thank you

**Comment by awsjason** [comment]
Correct: "S3 Copy Status" and the TimeoutSeconds?
The other part would be the nodejs script on the EC2 doing the copy.  The function that does the S3 upload may need to set the max part higher as well too.

Best of luck.  Let me know if you have other questions.
