### ISSUE TITLE
Exported Image lost a large number of file.

### ISSUE THREAD

**Issue by aws772623526** [awslabs/aws-gov-cloud-import#24]
I tried exporting two ami's from commercial region to govcloud. One of them migrated just fine the other one is missing a large number of files. Could you please suggest a fix for this issue. Both ebs volumes are of 50 gb in size.
Thank You!!

**Comment by awsjason** [comment]
Files on the EBS volume?  Not sure how that could happen and still pass vmimport validation on the other side as its doing a block for block copy.  Suggest trying again and see if its repeats itself.
