### ISSUE TITLE
New AMI IDs (longer format) not accepted by deployed web UI

### ISSUE THREAD

**Issue by trunderw** [awslabs/aws-gov-cloud-import#3]
![image](https://user-images.githubusercontent.com/785124/44168970-017dca80-a0a1-11e8-94ca-e7dcbd20187d.png)

The older, smaller AMI IDs still work as expected.

This is the culprit, which I fixed locally but wanted to let you know:

//Validate Image Input field
function validateImageFormat(){
    let image = document.getElementById("image").value;
    //Regex for ami/snap formatting
    if (/**^ami\-[a-f0-9]{8}$**|snap\-[a-f0-9]{17}$/.test(image)){
      console.log("valid image input")
    } else {
       $.mobile.changePage( "#noverify", { role: "dialog" } );
       document.getElementById("image").value = "";
    }
}

**Comment by awsjason** [comment]
Hi There, sorry for the delay.  Its been fixed.  You can just update the script if you like to 
`/^ami\-[a-f0-9]{8}$|ami\-[a-f0-9]{17}$|snap\-[a-f0-9]{17}$/.test(image)`

You can also reinstall which is not as much fun....  😀
