### ISSUE TITLE
[Security Concern] S3 Publicity

### ISSUE THREAD

**Issue by mikeford** [awslabs/aws-gov-cloud-import#30]
I hope this doesn't come off too alarmist, but I wanted to raise something I found while recently working with `aws-gov-cloud-import`.

**Summary**

I recently needed to use this tool to import an AMI from Commercial AWS into GovCloud AWS.

While doing so, I ran into a number of issues that caused the invocation of `gov-cloud-import-install.sh` to fail. This was ultimately due to my own misunderstanding, but nonetheless, one of the most time-consuming and frustrating parts was needing to input **two sets of admin-privileged AWS secrets** each time.

As the README states:

> You'll need API Keys with admin privileges for Commercial and GovCloud.

So, growing tired of inputting my AWS keys each time during the debug process, I realized how much easier my life would be each time if I just modified the shell script to hardcode my credentials.

But in thinking deeper, I realized this script is not just creating _some_ public S3 bucket -- it's literally copying the exact cloned `aws-gov-cloud-import` directory to a public S3 bucket. Any changes I would have made to `gov-cloud-import-install.sh` to make my debugging life a little bit easier would have been published to an S3 bucket.

Although I would love to think I am alone in having this lazy idea, I fear some developers using this tool might not stop to think what they're actually doing: they're publishing the current working directory publicly on the internet.

**Possible Remedies**
I think at a minimum, the CLI and README should have their copy updated to make it explicit that this is not just a public S3 bucket, but a public S3 bucket of the current working directory.

Ideally, I think the solution here is to exclude the `gov-cloud-import-install.sh` script from the s3 bucket.

At https://github.com/awslabs/aws-gov-cloud-import/blob/3d7aa6a9980d47e140662d8b9ec1a05a9fd3118e/gov-cloud-import-install.sh#L210 the command could be modified as

```
aws s3 sync ./ s3://gov-cloud-import-$RAND --quiet  --profile com12345 --exclude gov-cloud-import-install.sh
```

Thanks for building this tool! 😄

**Comment by awsjason** [comment]
Hey Mike, that's a well articulated concern and response.  Happy to make the update and make sense to exclude as its not needed.  Would like to add for posterity, if you don't augment the script there shouldn't be a security concern since its just a clone of the public code and the script echoes it's a public bucket as its needed for the UI.  Appreciate you using the tool and providing feedback.  Feel free to let us know if there are other concerns needing to be addressed.

**Comment by mikeford** [comment]
Awesome @awsjason, appreciate the quick response and glad I could help out.

Agree 100% on the posterity bit: this was in no way a reflection of the code itself being vulnerable, but more of a "some developers take shortcuts + don't fully read the code" potential pitfall that can be easily avoided.

**Comment by mikeford** [comment]
@awsjason On second look, I missed the presence of

https://github.com/awslabs/aws-gov-cloud-import/blob/65d3e59d809c0b97417957f53a121b39e8529f72/gov-cloud-import-install.sh#L239

in my original code walkthrough; an s3 sync occurs _twice_, so this second sync would still place the shell script in the bucket.

**Comment by awsjason** [comment]
Sry for the delay.  Will add the exclusion now.  Thanks for taking the time to be thorough.
