### ISSUE TITLE
AMIs with multiple EBS volumes aren't transferred

### ISSUE THREAD

**Issue by trunderw** [awslabs/aws-gov-cloud-import#4]
AMIs that are comprised of (maybe reference is the right term?) multiple EBS volumes aren't transferred when selecting the AMI id. I think the root block device was transferred but since the other volumes weren't transferred, fstab entries blocked it from starting. What I expected was that the AMI and its referenced block devices would be transferred and re-linked in gov. This may not have been the intended behavior but it sure would be nice.
I was able to transfer snapshots individually and rebuild the machine in govcloud -- so the tool does perform well in that regard.

**Comment by awsjason** [comment]
This is stated in the documentation that the script only does the root volume.  If you want additional volumes, you've figured out way to do it with this tool.  Please let me know if you run into an issue regarding it.
