### ISSUE TITLE
Question regarding S3 Bucket Limit

### ISSUE THREAD

**Issue by dpmcgarry** [awslabs/aws-gov-cloud-import#5]
First off, thanks for this tool.
We are looking to transfer a large dataset in S3 from Pub to Gov cloud.
In the description, it mentions a limit of 1TiB for transferring S3 data (or is this just a limit on live sync capability?).
What causes / creates the 1TiB limit?  We have more than 1TiB of data to move, we don't require sync, and we want to understand what is causing the limit so we can extend this code to overcome it if we need to.

**Comment by awsjason** [comment]
Glad to help!

The 1TiB limit is a soft limit.  The real limitation in the S3 StepFunction.  There is a limit on a timer.  You can always adjust the timer:

    "S3 Sync": {
      "Type": "Task",
      "Resource": "${s3s3Sync}",
      "TimeoutSeconds": 86400,  <--------- Here
      "HeartbeatSeconds": 300,
      "InputPath": "$",
      "ResultPath": "$.s3Status",
      "Next": "S3 Sync Finish?"
    },

Most 1TiB can be done in that limit and what was supportable.

You can play with it to customize albeit your off the reservation then and would love some notes on what happens with larger sizes.
