### ISSUE TITLE
S3 Copy Failed

### ISSUE THREAD

**Issue by immesys** [awslabs/aws-gov-cloud-import#7]
I'm trying to copy an AMI from us-east-2 to us-gov-east-1 (this is after ignoring the error in #6) and the state machine fails at "S3 Copy Status" with "S3 Copy Failed". 

Which logs should I look at? I can't seem to find any indication of why it would fail.

Both credentials (for standard and gov) have full administrator privileges.

**Comment by awsjason** [comment]
Try looking at the /gov-cloud-import/EC2Worker in cloudwatch logs.  This usually gives a clue to something like permissions or long those lines.

**Comment by abannerjee** [comment]
I came across the same issue. When I checked the EC2Worker cloudwatch log, I saw the following error:
```
InvalidBucketName: The specified bucket is not valid.
```

After some digging, I found my issue was the `gov-cloud-import-install.sh` script did not set the `gov-cloud-import-s3Bucket` SSM parameter. I needed to manually set that, and was able to then successfully copy the AMI.

**Comment by awsjason** [comment]
Awesome.  Please let me know if there is any other issues!

**Comment by immesys** [comment]
No this is a bug, it should be fixed. The script is supposed to set that for you

**Comment by awsjason** [comment]
Is it happening every install?

**Comment by immesys** [comment]
I tried several times and it failed every time. It never succeeded

**Comment by awsjason** [comment]
Gotcha, working on it this morning.

**Comment by awsjason** [comment]
Alright, found the issue.  Awk was grabbing the wrong text output of the describe cloudformation template.  Should be good.  Thanks for bringing it to attention.
