### ISSUE TITLE
Config govRegion and comRegion not correct when entering API Keys.

### ISSUE THREAD

**Issue by abannerjee** [awslabs/aws-gov-cloud-import#8]
According to the documentation, to import images, we need to first browse to the API Key page and enter keys. When you click “Validate” the `setRegionAndKeys()` function in gov-cloud-import-browser.js gets called and the following code runs:

```
config.govRegion = document.getElementById("govRegion").value;
console.log(config.govRegion+' Before')
if (config.govRegion != 'us-gov-west-1' && config.govRegion != 'us-gov-east-1'){
    config.govRegion = 'us-gov-west-1';
    console.log(config.govRegion+' During')
}
…
```

The problem here is at this point, the `<select>` element with id=govRegion has not been set yet. A second issue is there are actually two `<select>` elements in index.html with id=govRegion. Since it's not set, the govRegion and comRegion would default to 'west'.

To get around this, I needed to first browse to the Import Image page and set the regions, and then go back to the API Key Page and enter the keys and validate.

**Comment by awsjason** [comment]
Thanks for taking time to submit an issue!

I've put a region select on the validation page now.  Tested and show be good to go.  Please let me know if you run in to an issue.
